window.LONGSHANG_LANGUAGES = {
    'zh-Hant': {
        htmlLang: 'zh-Hant',
        title: 'LONGSHANG 龍殤 | 企業級 AI 閘道平台',
        description: 'LONGSHANG 龍殤 - 為團隊與企業打造的 AI API 閘道平台，整合多模型、權限管理、用量控管與社群支援。',
        languageLabel: '語言',
        themeToggle: '主題',
        brandLocal: '龍殤',
        heroBadge: '多模型整合 · 用量控管 · 團隊協作',
        heroSubtitle: '為企業、開發者與創作者打造的 AI API 閘道平台。<br>集中管理多家模型供應商，降低串接成本，讓團隊更穩定、更安全地使用 AI。',
        primaryCta: '立即開始使用',
        secondaryCta: '了解方案',
        discordCta: '加入 Discord 社群',
        telegramCta: '加入 Telegram 社群',
        proof1Label: '服務可用性目標',
        proof2Label: '可串接模型供應商',
        proof3Label: '用量與請求監控',
        whyTitle: '為什麼選擇 LONGSHANG？',
        whyText: '從 API 串接到用量治理，協助團隊把 AI 能力穩定導入日常工作流程。',
        stat1Title: '集中式模型管理',
        stat1Text: '在同一個平台管理 OpenAI、Claude、Gemini、DeepSeek、Grok 等模型。<br>開發團隊不必重複維護多套 API 串接邏輯。',
        stat2Title: '權限與安全控管',
        stat2Text: '依照團隊、專案與角色設定存取權限。<br>讓敏感金鑰與 AI 使用流程更容易被追蹤與管理。',
        stat3Title: '用量分析與預算控管',
        stat3Text: '即時掌握 Token 消耗、請求量與模型成本。<br>協助團隊控制預算，避免非預期的高額費用。',
        stat4Title: '穩定可靠的服務架構',
        stat4Text: '提供統一入口、備援策略與清楚的請求紀錄。<br>讓 AI 應用在正式環境中更容易維運。',
        featuresTitle: '打造更好管理的 AI 基礎設施',
        featuresText: '讓團隊把心力放在產品與流程，而不是分散在金鑰、帳單與供應商差異上。',
        feature1Title: '多模型快速串接',
        feature1Text: '透過統一 API 入口，快速切換不同模型與供應商。<br>支援 GPT、Claude、Gemini、DeepSeek、Grok 等主流模型，讓產品開發更有彈性。',
        feature2Title: '團隊協作與治理',
        feature2Text: '集中管理成員、專案、金鑰與使用規則。<br>讓管理者可以清楚掌握誰在使用 AI、如何使用，以及成本流向。',
        feature3Title: '透明用量與成本追蹤',
        feature3Text: '以清楚的數據呈現請求紀錄、Token 用量與成本趨勢。<br>協助團隊做出更好的模型選擇與資源配置。',
        securityBadge: '安全與治理',
        securityTitle: '讓每一次 AI 請求都有紀錄、有權限、有預算',
        securityText: 'LONGSHANG 協助團隊把 AI 使用從個人實驗提升為可管理的基礎設施，讓管理者能掌握風險、成本與服務品質。',
        securityPoint1: '金鑰集中保管，降低外洩風險',
        securityPoint2: '依專案分配額度與模型權限',
        securityPoint3: '保留請求紀錄，支援審計與除錯',
        securityPoint4: '用量異常時可快速調整策略',
        modelsTitle: '串起主流 AI 模型供應商',
        modelsText: '用同一套介面管理不同模型，依照任務自由選擇速度、成本與推理能力。',
        modelMore: '更多模型',
        workflowTitle: '三步驟導入 AI 閘道',
        workflowText: '從串接到治理，以清楚的流程把 AI 能力交付給整個團隊。',
        step1Title: '連接供應商',
        step1Text: '加入模型 API 金鑰，建立統一入口，讓不同服務使用相同的呼叫方式。',
        step2Title: '設定團隊規則',
        step2Text: '依照專案、角色與預算設定權限，確保每次請求都有清楚的歸屬。',
        step3Title: '追蹤並最佳化',
        step3Text: '透過用量與成本報表調整模型策略，讓品質、速度與費用取得平衡。',
        useCasesTitle: '適合這些 AI 工作流',
        useCasesText: 'LONGSHANG 可以成為產品、客服、營運與內部自動化的共同 AI 基礎層。',
        useCase1Title: '產品內建 AI 功能',
        useCase1Text: '為 SaaS、工具與平台加入摘要、生成、搜尋與助理能力。',
        useCase2Title: '客服與知識庫',
        useCase2Text: '整合多模型回覆、知識檢索與人工交接，提升回應品質。',
        useCase3Title: '內部自動化',
        useCase3Text: '讓營運、行銷與工程團隊用受控方式建立 AI 自動化流程。',
        finalCtaTitle: '準備把 AI 能力交給整個團隊了嗎？',
        finalCtaText: '從第一個 API 金鑰開始，把模型、權限、成本與監控集中到 LONGSHANG。',
        finalCtaButton: '開始建置 AI 閘道',
        finalCtaSecondary: '聯絡我們',
        footerBrand: 'LONGSHANG 龍殤',
        copyright: '© 2026 LONGSHANG. All Rights Reserved.'
    },
    'zh-Hans': {
        htmlLang: 'zh-Hans',
        title: 'LONGSHANG 龙殇 | 企业级 AI 网关平台',
        description: 'LONGSHANG 龙殇 - 为团队与企业打造的 AI API 网关平台，整合多模型、权限管理、用量控制与社群支持。',
        languageLabel: '语言',
        themeToggle: '主题',
        brandLocal: '龙殇',
        heroBadge: '多模型整合 · 用量控制 · 团队协作',
        heroSubtitle: '为企业、开发者与创作者打造的 AI API 网关平台。<br>集中管理多家模型供应商，降低接入成本，让团队更稳定、更安全地使用 AI。',
        primaryCta: '立即开始使用',
        secondaryCta: '了解方案',
        discordCta: '加入 Discord 社群',
        telegramCta: '加入 Telegram 社群',
        proof1Label: '服务可用性目标',
        proof2Label: '可接入模型供应商',
        proof3Label: '用量与请求监控',
        whyTitle: '为什么选择 LONGSHANG？',
        whyText: '从 API 接入到用量治理，帮助团队把 AI 能力稳定导入日常工作流程。',
        stat1Title: '集中式模型管理',
        stat1Text: '在同一个平台管理 OpenAI、Claude、Gemini、DeepSeek、Grok 等模型。<br>开发团队不必重复维护多套 API 接入逻辑。',
        stat2Title: '权限与安全控制',
        stat2Text: '按照团队、项目与角色设置访问权限。<br>让敏感密钥与 AI 使用流程更容易被追踪与管理。',
        stat3Title: '用量分析与预算控制',
        stat3Text: '实时掌握 Token 消耗、请求量与模型成本。<br>帮助团队控制预算，避免非预期的高额费用。',
        stat4Title: '稳定可靠的服务架构',
        stat4Text: '提供统一入口、备援策略与清晰的请求记录。<br>让 AI 应用在生产环境中更容易维护。',
        featuresTitle: '打造更易管理的 AI 基础设施',
        featuresText: '让团队把精力放在产品与流程，而不是分散在密钥、账单与供应商差异上。',
        feature1Title: '多模型快速接入',
        feature1Text: '通过统一 API 入口，快速切换不同模型与供应商。<br>支持 GPT、Claude、Gemini、DeepSeek、Grok 等主流模型，让产品开发更有弹性。',
        feature2Title: '团队协作与治理',
        feature2Text: '集中管理成员、项目、密钥与使用规则。<br>让管理员可以清楚掌握谁在使用 AI、如何使用，以及成本流向。',
        feature3Title: '透明用量与成本追踪',
        feature3Text: '以清晰的数据呈现请求记录、Token 用量与成本趋势。<br>帮助团队做出更好的模型选择与资源配置。',
        securityBadge: '安全与治理',
        securityTitle: '让每一次 AI 请求都有记录、有权限、有预算',
        securityText: 'LONGSHANG 帮助团队把 AI 使用从个人实验提升为可管理的基础设施，让管理员掌握风险、成本与服务质量。',
        securityPoint1: '密钥集中保管，降低泄露风险',
        securityPoint2: '按项目分配额度与模型权限',
        securityPoint3: '保留请求记录，支持审计与调试',
        securityPoint4: '用量异常时可快速调整策略',
        modelsTitle: '串起主流 AI 模型供应商',
        modelsText: '用同一套界面管理不同模型，按照任务自由选择速度、成本与推理能力。',
        modelMore: '更多模型',
        workflowTitle: '三步导入 AI 网关',
        workflowText: '从接入到治理，用清晰流程把 AI 能力交付给整个团队。',
        step1Title: '连接供应商',
        step1Text: '加入模型 API 密钥，建立统一入口，让不同服务使用相同的调用方式。',
        step2Title: '设置团队规则',
        step2Text: '按照项目、角色与预算设置权限，确保每次请求都有清楚归属。',
        step3Title: '追踪并优化',
        step3Text: '通过用量与成本报表调整模型策略，让质量、速度与费用取得平衡。',
        useCasesTitle: '适合这些 AI 工作流',
        useCasesText: 'LONGSHANG 可以成为产品、客服、运营与内部自动化的共同 AI 基础层。',
        useCase1Title: '产品内置 AI 功能',
        useCase1Text: '为 SaaS、工具与平台加入摘要、生成、搜索与助手能力。',
        useCase2Title: '客服与知识库',
        useCase2Text: '整合多模型回复、知识检索与人工交接，提升响应质量。',
        useCase3Title: '内部自动化',
        useCase3Text: '让运营、营销与工程团队用受控方式建立 AI 自动化流程。',
        finalCtaTitle: '准备把 AI 能力交给整个团队了吗？',
        finalCtaText: '从第一个 API 密钥开始，把模型、权限、成本与监控集中到 LONGSHANG。',
        finalCtaButton: '开始构建 AI 网关',
        finalCtaSecondary: '联系我们',
        footerBrand: 'LONGSHANG 龙殇',
        copyright: '© 2026 LONGSHANG. All Rights Reserved.'
    },
    en: {
        htmlLang: 'en',
        title: 'LONGSHANG | Enterprise AI Gateway Platform',
        description: 'LONGSHANG is an AI API gateway platform for teams and enterprises, combining multi-model access, permission control, usage governance, and community support.',
        languageLabel: 'Language',
        themeToggle: 'Theme',
        brandLocal: 'AI Gateway',
        heroBadge: 'Multi-model access · Usage control · Team collaboration',
        heroSubtitle: 'An AI API gateway platform built for enterprises, developers, and creators.<br>Manage multiple model providers in one place, reduce integration work, and help teams use AI with more stability and security.',
        primaryCta: 'Get Started',
        secondaryCta: 'View Plans',
        discordCta: 'Join Discord',
        telegramCta: 'Join Telegram',
        proof1Label: 'Availability Target',
        proof2Label: 'Model Providers',
        proof3Label: 'Usage And Request Monitoring',
        whyTitle: 'Why Choose LONGSHANG?',
        whyText: 'From API integration to usage governance, LONGSHANG helps teams bring AI into daily workflows with confidence.',
        stat1Title: 'Centralized Model Management',
        stat1Text: 'Manage OpenAI, Claude, Gemini, DeepSeek, Grok, and other models from one platform.<br>Development teams no longer need to maintain separate API integrations for every provider.',
        stat2Title: 'Permission And Security Controls',
        stat2Text: 'Set access permissions by team, project, and role.<br>Keep sensitive keys and AI usage easier to trace, audit, and manage.',
        stat3Title: 'Usage Analytics And Budget Control',
        stat3Text: 'Track token usage, request volume, and model costs in real time.<br>Help teams control budgets and avoid unexpected high expenses.',
        stat4Title: 'Reliable Service Architecture',
        stat4Text: 'Use a unified gateway, fallback strategy, and clear request logs.<br>Make AI applications easier to operate in production environments.',
        featuresTitle: 'AI Infrastructure That Is Easier To Manage',
        featuresText: 'Let your team focus on products and workflows instead of keys, invoices, and provider differences.',
        feature1Title: 'Fast Multi-model Integration',
        feature1Text: 'Switch between models and providers through a unified API gateway.<br>Support GPT, Claude, Gemini, DeepSeek, Grok, and other major models with more product flexibility.',
        feature2Title: 'Team Collaboration And Governance',
        feature2Text: 'Centrally manage members, projects, keys, and usage rules.<br>Give administrators clear visibility into who uses AI, how it is used, and where costs go.',
        feature3Title: 'Transparent Usage And Cost Tracking',
        feature3Text: 'Show request logs, token usage, and cost trends with clear data.<br>Help teams make better model choices and resource decisions.',
        securityBadge: 'Security And Governance',
        securityTitle: 'Give Every AI Request A Log, Permission, And Budget',
        securityText: 'LONGSHANG helps teams move AI usage from personal experiments to managed infrastructure, giving leaders visibility into risk, cost, and service quality.',
        securityPoint1: 'Centralize keys to reduce leakage risk',
        securityPoint2: 'Assign budgets and model permissions by project',
        securityPoint3: 'Keep request logs for auditing and debugging',
        securityPoint4: 'Adjust policy quickly when usage spikes',
        modelsTitle: 'Connect Leading AI Model Providers',
        modelsText: 'Manage different models through one interface and choose speed, cost, and reasoning strength for each task.',
        modelMore: 'More Models',
        workflowTitle: 'Adopt An AI Gateway In Three Steps',
        workflowText: 'Move from integration to governance with a clear process that delivers AI capability to the whole team.',
        step1Title: 'Connect Providers',
        step1Text: 'Add model API keys and create a unified entry point so different services can call AI in the same way.',
        step2Title: 'Set Team Rules',
        step2Text: 'Configure permissions by project, role, and budget so every request has clear ownership.',
        step3Title: 'Track And Optimize',
        step3Text: 'Use usage and cost reports to refine model strategy and balance quality, speed, and expense.',
        useCasesTitle: 'Built For These AI Workflows',
        useCasesText: 'LONGSHANG can become the shared AI foundation for products, support, operations, and internal automation.',
        useCase1Title: 'AI Features Inside Products',
        useCase1Text: 'Add summarization, generation, search, and assistant capabilities to SaaS products, tools, and platforms.',
        useCase2Title: 'Support And Knowledge Bases',
        useCase2Text: 'Combine multi-model responses, knowledge retrieval, and human handoff to improve response quality.',
        useCase3Title: 'Internal Automation',
        useCase3Text: 'Help operations, marketing, and engineering teams build controlled AI automation workflows.',
        finalCtaTitle: 'Ready To Bring AI Capability To Your Whole Team?',
        finalCtaText: 'Start with your first API key and centralize models, permissions, cost, and monitoring in LONGSHANG.',
        finalCtaButton: 'Build Your AI Gateway',
        finalCtaSecondary: 'Contact Us',
        footerBrand: 'LONGSHANG',
        copyright: '© 2026 LONGSHANG. All Rights Reserved.'
    },
    ja: {
        htmlLang: 'ja',
        title: 'LONGSHANG | エンタープライズ AI ゲートウェイ',
        description: 'LONGSHANG は、複数モデルの接続、権限管理、利用量管理、コミュニティサポートを統合した、チームと企業向けの AI API ゲートウェイです。',
        languageLabel: '言語',
        themeToggle: 'テーマ',
        brandLocal: 'AI ゲートウェイ',
        heroBadge: '複数モデル対応 · 利用量管理 · チーム連携',
        heroSubtitle: '企業、開発者、クリエイターのための AI API ゲートウェイプラットフォーム。<br>複数のモデルプロバイダーを一元管理し、連携コストを抑えながら、より安定して安全に AI を活用できます。',
        primaryCta: '今すぐ始める',
        secondaryCta: 'プランを見る',
        discordCta: 'Discord に参加',
        telegramCta: 'Telegram に参加',
        proof1Label: '可用性目標',
        proof2Label: '接続可能なモデルプロバイダー',
        proof3Label: '利用量とリクエスト監視',
        whyTitle: 'LONGSHANG が選ばれる理由',
        whyText: 'API 連携から利用量の管理まで、AI を日々の業務フローへ安定して導入できるよう支援します。',
        stat1Title: 'モデルの一元管理',
        stat1Text: 'OpenAI、Claude、Gemini、DeepSeek、Grok などのモデルを 1 つの平台で管理できます。<br>開発チームはプロバイダーごとの API 連携を個別に維持する必要がありません。',
        stat2Title: '権限とセキュリティ管理',
        stat2Text: 'チーム、プロジェクト、ロールごとにアクセス権限を設定できます。<br>機密キーと AI 利用フローを追跡、監査、管理しやすくします。',
        stat3Title: '利用分析と予算管理',
        stat3Text: 'Token 消費、リクエスト数、モデルコストをリアルタイムで把握できます。<br>予算を管理し、想定外の高額費用を防ぎます。',
        stat4Title: '安定したサービス構成',
        stat4Text: '統一された入口、フォールバック戦略、明確なリクエストログを提供します。<br>本番環境の AI アプリケーションを運用しやすくします。',
        featuresTitle: '管理しやすい AI 基盤を構築',
        featuresText: 'キー、請求、プロバイダーごとの差分に時間を奪われず、チームが製品と業務フローに集中できます。',
        feature1Title: '複数モデルへの素早い接続',
        feature1Text: '統一 API ゲートウェイを通じて、モデルとプロバイダーを素早く切り替えられます。<br>GPT、Claude、Gemini、DeepSeek、Grok などの主要モデルに対応し、プロダクト開発の柔軟性を高めます。',
        feature2Title: 'チーム連携とガバナンス',
        feature2Text: 'メンバー、プロジェクト、キー、利用ルールを一元管理できます。<br>誰が AI を使い、どのように利用し、コストがどこへ流れているかを明確に把握できます。',
        feature3Title: '透明な利用量とコスト追跡',
        feature3Text: 'リクエストログ、Token 利用量、コスト推移をわかりやすいデータで表示します。<br>より良いモデル選択とリソース配分を支援します。',
        securityBadge: 'セキュリティとガバナンス',
        securityTitle: 'すべての AI リクエストにログ、権限、予算を',
        securityText: 'LONGSHANG は、個人の実験としての AI 利用を管理可能な基盤へ引き上げ、リスク、コスト、サービス品質を把握できるようにします。',
        securityPoint1: 'キーを集中管理し、漏えいリスクを低減',
        securityPoint2: 'プロジェクトごとに予算とモデル権限を割り当て',
        securityPoint3: '監査とデバッグに使えるリクエストログを保存',
        securityPoint4: '利用量の急増時にポリシーを素早く調整',
        modelsTitle: '主要な AI モデルプロバイダーを接続',
        modelsText: '1 つのインターフェースで複数のモデルを管理し、タスクに応じて速度、コスト、推論能力を選べます。',
        modelMore: 'その他のモデル',
        workflowTitle: '3 ステップで AI ゲートウェイを導入',
        workflowText: '連携からガバナンスまで、明確な流れで AI 機能をチーム全体に届けます。',
        step1Title: 'プロバイダーを接続',
        step1Text: 'モデル API キーを追加し、統一された入口を作ることで、各サービスが同じ方法で AI を呼び出せます。',
        step2Title: 'チームルールを設定',
        step2Text: 'プロジェクト、ロール、予算に応じて権限を設定し、すべてのリクエストの所有者を明確にします。',
        step3Title: '追跡して最適化',
        step3Text: '利用量とコストのレポートをもとにモデル戦略を調整し、品質、速度、費用のバランスを取ります。',
        useCasesTitle: 'さまざまな AI ワークフローに対応',
        useCasesText: 'LONGSHANG は、プロダクト、サポート、運用、社内自動化の共通 AI 基盤になります。',
        useCase1Title: 'プロダクト内の AI 機能',
        useCase1Text: 'SaaS、ツール、プラットフォームに要約、生成、検索、アシスタント機能を追加できます。',
        useCase2Title: 'サポートとナレッジベース',
        useCase2Text: '複数モデルの回答、ナレッジ検索、有人対応を組み合わせて応答品質を高めます。',
        useCase3Title: '社内自動化',
        useCase3Text: '運用、マーケティング、エンジニアリングチームが管理された AI 自動化フローを構築できます。',
        finalCtaTitle: 'AI 機能をチーム全体に届ける準備はできましたか？',
        finalCtaText: '最初の API キーから始めて、モデル、権限、コスト、監視を LONGSHANG に集約しましょう。',
        finalCtaButton: 'AI ゲートウェイを構築',
        finalCtaSecondary: 'お問い合わせ',
        footerBrand: 'LONGSHANG',
        copyright: '© 2026 LONGSHANG. All Rights Reserved.'
    }
};
